name: STRrewardZone
main: ru.strid.strreward.STRrewardZone
description: Plugin for giving rewards to players who reach specific regions on the map.
version: 1.0
api-version: 1.21
commands:
  rewardzone:
    usage: /rewardzone <create/delete/modify> <zoneName>
    permission: str.reward.crud
  rewardtable:
    usage: /rewardtable <create/delete/modify> <tableName>
    permission: str.reward.crud
  rewardregion:
    usage: /rewardregion <pos1/pos2/clear>
    aliases:
      - rewardrg
      - rrg
    permission: str.reward.crud
  rewardload:
    usage: /rewardload
    aliases:
      - rload
    permission: str.reward.crud